-- Sabiora website — starting content for the services, projects and tech stack tables.
-- GENERATED by scripts/generate-seed.mjs from lib/data.ts. Do not edit by hand; run `npm run seed:generate`.
--
-- Run supabase/schema.sql first, then this file, in the Supabase SQL editor.
-- It only adds rows that are missing, so it is safe to run again and never overwrites your edits.

-- ------------------------------------------------------------------ services

insert into public.services (id, title, blurb, features, details, body_md, visual, span, sort_order)
values ('mobile-app', 'Mobile App Development', 'Android and iOS apps that feel native, stay reliable and are built to scale — for businesses, startups and organizations.',
  array['Android & iOS', 'Cross-platform', 'Business & enterprise apps', 'Booking & on-demand apps']::text[],
  array['Android & iOS applications', 'Cross-platform mobile apps', 'Enterprise & business apps', 'E-commerce & marketplace apps', 'Booking & appointment apps', 'On-demand service apps', 'API & third-party integrations', 'Maintenance & support']::text[],
  '', 'phones', 2, 10)
on conflict (id) do nothing;

insert into public.services (id, title, blurb, features, details, body_md, visual, span, sort_order)
values ('website', 'Website Development', 'Fast, responsive, search-friendly websites that give your business a credible digital presence.',
  array['React / Next.js', 'Landing pages', 'CMS & WordPress', 'Redesigns']::text[],
  array['Business & corporate sites', 'Custom websites & landing pages', 'E-commerce & WordPress sites', 'Booking & reservation sites', 'Educational & institutional sites', 'Content management systems', 'Redesign & modernization', 'Maintenance & security']::text[],
  '', 'browser', 1, 20)
on conflict (id) do nothing;

insert into public.services (id, title, blurb, features, details, body_md, visual, span, sort_order)
values ('ecommerce', 'E-Commerce Solutions', 'Secure online stores — catalogue, cart, checkout and payments, wired into delivery and reporting.',
  array['Online stores', 'Payment gateways', 'Orders & delivery']::text[],
  array['Online store development', 'Product & inventory management', 'Shopping cart & checkout', 'Payment gateway integration', 'Order & customer accounts', 'Delivery integrations', 'Notifications & communication', 'E-commerce admin & reporting']::text[],
  '', 'checkout', 1, 30)
on conflict (id) do nothing;

insert into public.services (id, title, blurb, features, details, body_md, visual, span, sort_order)
values ('cloud', 'Cloud & DevOps', 'Containerized deployments and automated pipelines on dependable cloud infrastructure, so shipping is routine instead of risky.',
  array['Docker & containers', 'CI/CD pipelines', 'Deployment automation', 'Monitoring & backups']::text[],
  array['Cloud application deployment', 'Server & infrastructure configuration', 'Docker & containerization', 'CI/CD pipeline setup', 'Deployment automation', 'Domain & SSL configuration', 'Infrastructure management', 'Monitoring, backups & support']::text[],
  '', 'pipeline', 2, 40)
on conflict (id) do nothing;

insert into public.services (id, title, blurb, features, details, body_md, visual, span, sort_order)
values ('uiux', 'UI/UX Design', 'Clear, consistent interfaces — from user flows and wireframes to prototypes and design systems.',
  array['User flows', 'Prototypes', 'Design systems']::text[],
  array['UI design & UX planning', 'User flows & wireframes', 'Interactive prototypes', 'Mobile application design', 'Website design', 'Design systems', 'Responsive interface design']::text[],
  '', 'canvas', 1, 50)
on conflict (id) do nothing;

insert into public.services (id, title, blurb, features, details, body_md, visual, span, sort_order)
values ('api', 'API & System Integration', 'APIs and integrations that let your apps, platforms and third-party services talk securely.',
  array['REST APIs', 'Auth & authorization', 'Payments, SMS & email']::text[],
  array['REST API development', 'Third-party API integration', 'Payment gateway integration', 'Authentication & authorization', 'SMS & email integrations', 'Cloud service integration', 'Business system integration', 'Data & service integrations']::text[],
  '', 'api', 1, 60)
on conflict (id) do nothing;

insert into public.services (id, title, blurb, features, details, body_md, visual, span, sort_order)
values ('web-apps', 'Web Apps & Custom Software', 'Software shaped around how your business actually works — its processes, users and requirements.',
  array['CRM & HR systems', 'Inventory & booking', 'Dashboards & SaaS']::text[],
  array['Business management systems', 'CRM & HR management systems', 'Inventory management systems', 'Booking & reservation platforms', 'Dashboards & admin portals', 'SaaS applications', 'Workflow & business automation', 'Custom internal business tools']::text[],
  '', 'dashboard', 1, 70)
on conflict (id) do nothing;

insert into public.services (id, title, blurb, features, details, body_md, visual, span, sort_order)
values ('maintenance', 'Maintenance & Scaling', 'Launch is only the beginning. We keep your product secure, fast and up to date — and help it grow with your business.',
  array['Security updates', 'Performance tuning', 'Feature enhancements', 'Technical consulting', 'Modernization']::text[],
  array['Application & site maintenance', 'Bug fixing & troubleshooting', 'Security updates', 'Performance improvements', 'Feature enhancements', 'Infrastructure support', 'Technical consultation', 'System modernization']::text[],
  '', 'uptime', 3, 80)
on conflict (id) do nothing;

-- ------------------------------------------------------------------ projects

insert into public.projects (slug, title, category, platform, industry, description, highlight, highlights, body_md,
  image_url, image_width, image_height, tags, client, year, featured, links, sort_order)
values ('fashion-rental-platform', 'Fashion Try-Before-You-Buy Platform', 'Web Application', 'web',
  array['Fashion', 'E-commerce']::text[],
  'Rental-to-own fashion commerce platform combining serialized inventory tracking, dispatch-triggered rental windows, and automated conversion-to-purchase settlement, built on an event-driven backend.',
  'Event-driven backend',
  array['Serialized inventory tracking', 'Dispatch-triggered rental windows', 'Automated conversion-to-purchase settlement', 'Event-driven backend on Kafka']::text[],
  '',
  '/images/projects/fashion-rental-platform.webp', 1280, 775,
  array['Spring Boot', 'React', 'PostgreSQL', 'Kafka', 'Redis', 'MinIO']::text[], 'FashionMart', '2026', true,
  '[]'::jsonb, 10)
on conflict (slug) do nothing;

insert into public.projects (slug, title, category, platform, industry, description, highlight, highlights, body_md,
  image_url, image_width, image_height, tags, client, year, featured, links, sort_order)
values ('cafe-management-system', 'Cafe Management System', 'Business Software', 'web',
  array['Hospitality', 'Operations']::text[],
  'Full-stack cafe operations platform — QR ordering, POS, inventory, and real-time kitchen display, with role-based access across 8 staff roles.',
  '8 staff roles, one platform',
  array['QR table ordering', 'Point of sale', 'Inventory management', 'Real-time kitchen display', 'Role-based access across 8 staff roles']::text[],
  '',
  '/images/projects/cafe-management-system.webp', 1280, 710,
  array['Spring Boot', 'Angular', 'PostgreSQL', 'Kafka', 'Redis']::text[], 'Personal Project', '2026', true,
  '[]'::jsonb, 20)
on conflict (slug) do nothing;

insert into public.projects (slug, title, category, platform, industry, description, highlight, highlights, body_md,
  image_url, image_width, image_height, tags, client, year, featured, links, sort_order)
values ('aora-receipts-expenses', 'Aora: Smart Receipt & Expense Tracker', 'Mobile Application', 'mobile',
  array['Personal finance', 'Mobile']::text[],
  'Snap receipts, let AI organize the details, and keep your expenses in one place. Built with privacy and offline use in mind.',
  'Live on iOS & Android',
  array['Snap a receipt to capture an expense', 'AI organizes the details', 'Built with privacy in mind', 'Works offline']::text[],
  '',
  '/images/projects/aora.webp', 640, 1391,
  array['Flutter']::text[], 'Sample Project', '2026', true,
  '[{"label":"App Store","url":"https://apps.apple.com/us/app/aora-receipts-expenses/id6752373417"},{"label":"Google Play","url":"https://play.google.com/store/apps/details?id=com.noor.aura"}]'::jsonb, 30)
on conflict (slug) do nothing;

insert into public.projects (slug, title, category, platform, industry, description, highlight, highlights, body_md,
  image_url, image_width, image_height, tags, client, year, featured, links, sort_order)
values ('unvoid', 'Unvoid: Flip Your Phone. Reclaim Your Time.', 'Mobile Application', 'mobile',
  array['Wellbeing', 'Mobile']::text[],
  'A simple focus app built around one physical habit: flip your phone face down and step away from the screen.',
  'Live on the App Store',
  array['One physical habit: flip your phone face down', 'Step away from the screen and focus']::text[],
  '',
  '/images/projects/unvoid.webp', 640, 1391,
  array['Flutter']::text[], 'Sample Project', '2026', false,
  '[{"label":"App Store","url":"https://apps.apple.com/us/app/unvoid/id6759614758"}]'::jsonb, 40)
on conflict (slug) do nothing;

-- ------------------------------------------------------------------ tech stack

insert into public.tech_categories (id, label, summary, sort_order)
values ('backend', 'Backend', 'Service layers that carry the business logic — typed, tested and event-driven where it pays off.', 10)
on conflict (id) do nothing;

insert into public.tech_categories (id, label, summary, sort_order)
values ('frontend', 'Frontend', 'Interfaces for the web and for phones, built from reusable components and real design systems.', 20)
on conflict (id) do nothing;

insert into public.tech_categories (id, label, summary, sort_order)
values ('data', 'Database & Messaging', 'Durable storage, fast reads and event streams that keep separate services in step.', 30)
on conflict (id) do nothing;

insert into public.tech_categories (id, label, summary, sort_order)
values ('devops', 'DevOps', 'Repeatable builds and automated releases, from a commit to a running container.', 40)
on conflict (id) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('Java', 'Jv', 'Core service language', 'backend', 10)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('Spring Boot', 'SB', 'APIs & business logic', 'backend', 20)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('Node.js', 'Nd', 'Realtime services', 'backend', 30)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('React', 'Re', 'Web application UIs', 'frontend', 40)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('Next.js', 'Nx', 'Fast, SEO-ready sites', 'frontend', 50)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('Angular', 'Ng', 'Enterprise front-ends', 'frontend', 60)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('Flutter', 'Fl', 'iOS & Android apps', 'frontend', 70)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('PostgreSQL', 'Pg', 'Primary relational data', 'data', 80)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('Kafka', 'Kf', 'Event streaming', 'data', 90)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('Redis', 'Rd', 'Caching & sessions', 'data', 100)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('MinIO', 'Mi', 'Object storage', 'data', 110)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('Docker', 'Dk', 'Containerized builds', 'devops', 120)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('Kubernetes', 'K8', 'Orchestration & rollouts', 'devops', 130)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('CI/CD', 'CI', 'Automated pipelines', 'devops', 140)
on conflict (name) do nothing;

insert into public.technologies (name, abbr, purpose, category_id, sort_order)
values ('AWS', 'Aw', 'Cloud hosting', 'devops', 150)
on conflict (name) do nothing;

notify pgrst, 'reload schema';
