/**
 * generate-seed.mjs — Writes supabase/seed.sql from the default content in lib/data.ts.
 *
 * Run with `npm run seed:generate` after changing the defaults. The SQL it produces only inserts
 * rows that are not there yet (`on conflict do nothing`), so running it in Supabase never
 * overwrites something edited in the dashboard.
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { projects, services, stack } from '../lib/data.ts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const text = (value) => `'${String(value ?? '').replace(/'/g, "''")}'`;
const list = (values) => (values?.length ? `array[${values.map(text).join(', ')}]::text[]` : `'{}'::text[]`);
const json = (value) => `${text(JSON.stringify(value ?? []))}::jsonb`;

const lines = [
  '-- Sabiora website — starting content for the services, projects and tech stack tables.',
  '-- GENERATED by scripts/generate-seed.mjs from lib/data.ts. Do not edit by hand; run `npm run seed:generate`.',
  '--',
  '-- Run supabase/schema.sql first, then this file, in the Supabase SQL editor.',
  '-- It only adds rows that are missing, so it is safe to run again and never overwrites your edits.',
  '',
  '-- ------------------------------------------------------------------ services',
  '',
];

services.forEach((service, index) => {
  lines.push(
    'insert into public.services (id, title, blurb, features, details, body_md, visual, span, sort_order)',
    `values (${text(service.id)}, ${text(service.title)}, ${text(service.blurb)},`,
    `  ${list(service.features)},`,
    `  ${list(service.details)},`,
    `  ${text(service.body)}, ${text(service.visual)}, ${service.span}, ${(index + 1) * 10})`,
    'on conflict (id) do nothing;',
    '',
  );
});

lines.push('-- ------------------------------------------------------------------ projects', '');

projects.forEach((project, index) => {
  lines.push(
    'insert into public.projects (slug, title, category, platform, industry, description, highlight, highlights, body_md,',
    '  image_url, image_width, image_height, tags, client, year, featured, links, sort_order)',
    `values (${text(project.id)}, ${text(project.title)}, ${text(project.category)}, ${text(project.platform)},`,
    `  ${list(project.industry)},`,
    `  ${text(project.description)},`,
    `  ${text(project.highlight)},`,
    `  ${list(project.highlights)},`,
    `  ${text(project.body)},`,
    `  ${text(project.image.src)}, ${project.image.width}, ${project.image.height},`,
    `  ${list(project.tags)}, ${text(project.client)}, ${text(project.year)}, ${project.featured},`,
    `  ${json(project.links)}, ${(index + 1) * 10})`,
    'on conflict (slug) do nothing;',
    '',
  );
});

lines.push('-- ------------------------------------------------------------------ tech stack', '');

stack.forEach((category, index) => {
  lines.push(
    'insert into public.tech_categories (id, label, summary, sort_order)',
    `values (${text(category.id)}, ${text(category.label)}, ${text(category.summary)}, ${(index + 1) * 10})`,
    'on conflict (id) do nothing;',
    '',
  );
});

let order = 0;
for (const category of stack) {
  for (const tech of category.techs) {
    order += 10;
    lines.push(
      'insert into public.technologies (name, abbr, purpose, category_id, sort_order)',
      `values (${text(tech.name)}, ${text(tech.abbr)}, ${text(tech.use)}, ${text(category.id)}, ${order})`,
      'on conflict (name) do nothing;',
      '',
    );
  }
}

lines.push("notify pgrst, 'reload schema';", '');

await writeFile(path.join(root, 'supabase', 'seed.sql'), lines.join('\n'));
console.log(
  `supabase/seed.sql written: ${services.length} services, ${projects.length} projects, ${stack.length} categories, ${order / 10} technologies`,
);
